# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 23:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HiScript', models.TextField(max_length=1000)),
                ('ThanksScript', models.TextField(max_length=1000)),
                ('ApplicationDateMature', models.TextField(max_length=1000)),
                ('ApplicationDateYear12', models.TextField(max_length=1000)),
                ('ApplicationDateGeneric', models.TextField(max_length=1000)),
                ('AcceptingApplicationsNo', models.TextField(max_length=1000)),
                ('AcceptingApplicationsPG', models.TextField(max_length=1000)),
                ('AcceptingApplications12', models.TextField(max_length=1000)),
                ('AcceptingApplicationsMT', models.TextField(max_length=1000)),
                ('AcceptingApplicationsINT', models.TextField(max_length=1000)),
                ('AdmissionInfo', models.TextField(max_length=1000)),
                ('PathwaysInfo', models.TextField(max_length=1000)),
                ('ScholarshipInfo', models.TextField(max_length=1000)),
                ('AdvancedStandingInfo', models.TextField(max_length=1000)),
                ('close_off_DOM', models.TextField(max_length=1000)),
                ('close_off_INT', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
