# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 02:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advancedstanding', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Queryer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidqueryer', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=15)),
                ('international', models.BooleanField()),
                ('pathways', models.BooleanField()),
                ('scholarship', models.BooleanField()),
                ('advancedstanding', models.BooleanField()),
                ('year12', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='output',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Queryer'),
        ),
    ]
